### ISSUE TITLE
Does not work python >= 3.11

### ISSUE THREAD

**Issue by flyingfalling** [SpikeGadgets/TrodesNetwork#1]
Due to changes in C macros etc., trodesnetwork does not work with greater than python 3.10.

I can force it to compile the C side by changing all

`Py_SIZE(X) = YYYY;`

to

`Py_SET_SIZE(X, YYY);
`

In this case, the only instance of it is in the boost lib:

pythonPackaging/boost/include/boost/python/object/make_instance.hpp 

However, the cython development libraries layout/organization seems to have also changed. For example, simple pip install trodesnetwork from py3.11 or py 3.12 both fail with:

```
zmq/backend/cython/_device.c:196:12: fatal error: longintrepr.h: No such file or directory
        196 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~

```

This is due to a changing layout of the cython libs/headers in the 3.11/3.12 ZMQ, versus the settings during installation of trodesnetwork.

**Comment by flyingfalling** [comment]
Setting a symlink of that longintrepr.h file resolves that issue of course, but then many more errors arise. I will investigate in more detail when I have time.

**Comment by flyingfalling** [comment]
I have confirmed this is an issue with the pyzmq<20 dependency, which no longer compiles on newer systems due to changes in the Cython bindings (https://github.com/zeromq/pyzmq/issues/1697). It seems that only pyzmq>=23.0 is sufficient to enable python>=3.11 support.

Since this is not directly related to trodesnetwork but rather due to its reliance on old versions of another package (pyzmq), I'll close it. But it would be nice to be able to use on newer systems.
